import { prisma } from "@/lib/prisma";
import { WorkflowDefinition } from "@/lib/workflow/schema";

/**
 * Seed demo workflow: Google Form → AI Email → Gmail Send
 * 
 * When someone fills the Google Form, this workflow:
 * 1. Receives the form submission
 * 2. AI generates a personalized thank-you email
 * 3. Gmail sends the email to the submitter
 */

async function seedGoogleFormWorkflow() {
  console.log("🔨 Creating Google Form → AI Email → Gmail workflow...\n");

  // Find or use first user (you need a valid user to own the workflow)
  const user = await prisma.user.findFirst();
  if (!user) {
    throw new Error("No users found. Please sign in first to create a user.");
  }

  console.log(`Using user: ${user.email || user.name || user.id}`);

  // Extract form ID from the Google Form link
  const formId = "1FAIpQLSeH9Vq4GosuJiCLT0EnzPzOU7da8YGkkaffYk8lUdeJHfzjyw";

  // Define the workflow with 3 nodes
  const definition: WorkflowDefinition = {
    nodes: [
      {
        id: "trigger_form",
        type: "google_forms.trigger.newResponse",
        config: {
          connectionId: "stub-conn",
          formId: formId,
          since: undefined,
        },
      },
      {
        id: "ai_email",
        type: "ai.action.generateEmail",
        config: {
          instructions: "Write a warm, friendly thank-you email acknowledging their form submission. Keep it short and professional.",
        },
      },
      {
        id: "gmail_send",
        type: "gmail.action.sendEmail",
        config: {
          connectionId: "stub-conn",
          to: "roshangawade160@gmail.com", // User's email for demo
          subject: "{{subject}}", // Generated by AI node
          body: "{{body}}", // Generated by AI node
        },
      },
    ],
    edges: [
      { from: "trigger_form", to: "ai_email" },
      { from: "ai_email", to: "gmail_send" },
    ],
    ui: {
      positions: {
        trigger_form: { x: 100, y: 100 },
        ai_email: { x: 400, y: 100 },
        gmail_send: { x: 700, y: 100 },
      },
    },
  };

  // Create workflow
  const workflow = await prisma.workflow.create({
    data: {
      name: "Google Form Auto-Reply Demo",
      userId: user.id,
      status: "ACTIVE", // Make it immediately runnable
      definition: definition as any,
    },
  });

  console.log(`\n✅ Workflow created successfully!`);
  console.log(`Workflow ID: ${workflow.id}`);
  console.log(`Status: ${workflow.status}`);
  console.log(`\n🔗 Open in builder:`);
  console.log(`   http://localhost:3000/workflows/${workflow.id}/builder`);
  console.log(`\n🧪 Test execution:`);
  console.log(`   1. Go to: http://localhost:3000/dashboard`);
  console.log(`   2. Find your workflow and click "Execute"`);
  console.log(`   OR use this curl command:`);
  console.log(`   curl -X POST http://localhost:3000/api/workflows/${workflow.id}/execute -H "Content-Type: application/json" -d "{}"`);
  console.log(`\n📋 Workflow steps:`);
  console.log(`   1. ✅ Google Form trigger (mock data)`);
  console.log(`   2. ✅ AI generates email subject + body`);
  console.log(`   3. ✅ Gmail sends email (mock)`);
  console.log(`\n💡 Next steps:`);
  console.log(`   - Update the "to" field in Gmail node if your form uses a different email field name`);
  console.log(`   - For real Google Forms integration, you'll need to set up OAuth and actual API calls`);

  return workflow;
}

seedGoogleFormWorkflow()
  .catch((error) => {
    console.error("❌ Error creating workflow:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
